version: "3"

services:
  fiber:
    container_name: "resume-api-go"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - fileName: ".env"
    ports:
      - "8001:8001"
    restart: always
